name: Validate Community Events Data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate_community_events_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: 'v4.9.5'
      - run: |
         jsonschema -i <(yq eval --tojson -j data/events.yml) data/schemas/events.json
         echo "community events data is valid!"
